### ISSUE TITLE
i have no clue why this is happening  failed to infer ffmpeg?

### ISSUE THREAD

**Issue by tomas122727** [effusiveperiscope/so-vits-svc#41]
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\so-vits-svc-5.0-main\inference_gui.py", line 1076, in convert
    audio_data = load_audio(clean_name)
  File "M:\so-vits-svc-5.0-main\whisper\audio.py", line 48, in load_audio
    except ffmpeg.Error as e:
AttributeError: module 'ffmpeg' has no attribute 'Error'

**Comment by effusiveperiscope** [comment]
seems related https://github.com/kkroening/ffmpeg-python/issues/174

**Comment by tomas122727** [comment]
new problem 

RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "M:\so-vits-svc-5.0-main\inference_gui.py", line 1090, in convert
    out_audio = self.infer_tool.infer(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\so-vits-svc-5.0-main\inference_util.py", line 214, in infer
    vec = np.array(self.pred_vec(audio_data))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\so-vits-svc-5.0-main\inference_util.py", line 93, in pred_vec
    vec = self.hubert.units(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomas_000\miniconda3\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "M:\so-vits-svc-5.0-main\hubert\hubert_model.py", line 71, in units
    x, _ = self.encode(wav)
           ^^^^^^^^^^^^^^^^
  File "M:\so-vits-svc-5.0-main\hubert\hubert_model.py", line 41, in encode
    x = self.feature_extractor(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomas_000\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\so-vits-svc-5.0-main\hubert\hubert_model.py", line 88, in forward
    x = t_func.gelu(self.norm0(self.conv0(x)))
                               ^^^^^^^^^^^^^
  File "C:\Users\tomas_000\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomas_000\miniconda3\Lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomas_000\miniconda3\Lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by tomas122727** [comment]
UPDATE i just fixed it its working now i had to reinstall pytorch and torch audio

**Comment by effusiveperiscope** [comment]
OK
