### ISSUE TITLE
not inferring

### ISSUE THREAD

**Issue by tomas122727** [effusiveperiscope/so-vits-svc#45]
Error code
C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loading Fluttershy
models\Fluttershy\singer\Fluttershy.spk.npy
Traceback (most recent call last):
  File "M:\so-vits-svc-5.0-main\inference_gui.py", line 1149, in convert
    out_audio = self.infer_tool.infer(
  File "M:\so-vits-svc-5.0-main\inference_util.py", line 302, in infer
    vec = np.array(self.pred_vec(audio_data))
  File "M:\so-vits-svc-5.0-main\inference_util.py", line 129, in pred_vec
    vec = self.hubert.units(
  File "C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "M:\so-vits-svc-5.0-main\hubert\hubert_model.py", line 71, in units
    x, _ = self.encode(wav)
  File "M:\so-vits-svc-5.0-main\hubert\hubert_model.py", line 42, in encode
    x = self.feature_projection(x.transpose(1, 2))
  File "C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "M:\so-vits-svc-5.0-main\hubert\hubert_model.py", line 106, in forward
    x = self.norm(x)
  File "C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\nn\modules\normalization.py", line 201, in forward
    return F.layer_norm(
  File "C:\Users\tomas_000\miniconda3\envs\so_svc5\lib\site-packages\torch\nn\functional.py", line 2546, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

how to fix this also what python version am i suppose to install on my pc ?

**Comment by effusiveperiscope** [comment]
The hubert model is loaded in half precision mode to save memory. I suspect it may not work on CPU inference, but I am not in a position to test right now. Do you know if pytorch can see your GPU? 

I do not know exactly what python version is required, but my conda environment for so-vits-svc 5.0 uses python 3.10.13.

**Comment by tomas122727** [comment]
yes it can

**Comment by tomas122727** [comment]
even my previous so vits 4.0 works fine and so vits svc 3.0 works fine

**Comment by tomas122727** [comment]
it also keeps saying this at launch INFO: Could not find files for the given pattern(s).

**Comment by tomas122727** [comment]
nevermind i just fixed it by reinstalling torchcrepe module

**Comment by tomas122727** [comment]
it wasnt compiled by cuda keep this issue archieved in case someone runs into this
